import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
//import Nav from "./components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Carolina Mattos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        style={{
          backgroundImage: "url(/images/background.svg)",
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",

        }}
         className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full`}
      >
        <Header />        
        {children}
        
      </body>
    </html>
  );
}

