import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Analytics } from "@vercel/analytics/next"

//import Nav from "./components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Carolina Mattos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        style={{
          backgroundImage: "url(/images/background.svg)",
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",

        }}
         className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full`}
      >
        <Header />        
        {children}
        <Analytics />
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-Q59XK9HG6N"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-Q59XK9HG6N');
        </script>
      </body>
    </html>
  );
}

